### ISSUE TITLE
CBPI 4.0.0.32 not starting if mqtt is set to false

### ISSUE THREAD

**Issue by avollkopf** [Manuel83/craftbeerpi4#58]
If mqtt is set to false in config. cbpi is not starting and shows an exception.

It starts, when mqtt is set to true, but shows warnings from sattelite_controller since no mqtt connection can be established.

**Comment by avollkopf** [comment]
Issue is caused by craftbeerpi.py as sattelite controller is not started if mqtt is false

```
        self.satellite = None
        if self.static_config.get("mqtt", False) is True:
            self.satellite: SatelliteController = SatelliteController(self)
```

**Comment by Schullebernd** [comment]
It's because in the craftbeerpi.py the method push_update tries to send updated even there is no satellite defined:
```
def push_update(self, topic, data, retain=False) -> None:
            asyncio.create_task(self.satellite.publish(topic=topic, message=json.dumps(data), retain=retain))
```

chinging this to:
```
def push_update(self, topic, data, retain=False) -> None:
        if self.satellite is not None:
            asyncio.create_task(self.satellite.publish(topic=topic, message=json.dumps(data), retain=retain))
```
did it for me.

MQTT support seems to become one of a basic feature in cbpi4. The last commit shows that almost everywhere the push_update mechanism was integrated/adopted for mqtt.

**Comment by avollkopf** [comment]
@Schullebernd Great, looks way better

**Comment by Manuel83** [comment]
Fixed!

**Comment by avollkopf** [comment]
Working with 4.0.0.33
