### ISSUE TITLE
How can you query the current temperature of a kettle

### ISSUE THREAD

**Issue by JamFfm** [Manuel83/craftbeerpi4#69]
How can you query the current temperature of a kettle (via kettle_ID)?
and:
How can you query the current value of a sensor (via sensor ID)?

**Comment by avollkopf** [comment]
There are a few examples in my cbpi4-BM_Steps Plugin:
If you have the sensor as property:
`Property.Sensor(label="Sensor", description="Sensor that is used during cooldown")`

you can retrieve the value  with this line:
`sensor_value = self.get_sensor_value(self.props.get("Sensor")).get("value")`

You can use also the information from the steps that you query in your LCD Plugin and use that id instead of self.props.get("Sensor").

I did a quick and dirty test for the LCD screen which I can send you later as an example when I have access to my pi if you want.

**Comment by JamFfm** [comment]
yes please, that would be nice

**Comment by avollkopf** [comment]
@JamFfm This is a quick and dirty version of your pluign which is showing standby if no step is active and individual step information is brewing staps are active. I was just putting this together to run a test brew and to see what's going on as I have no touch screen.

[__init__.zip](https://github.com/Manuel83/craftbeerpi4/files/6319562/__init__.zip)

The hop alarms can also be used 'globally' as Manuel integrated that with the latest merge of my pull request for the 'native' boilstep.

Feel free to use whatever you need. Looking forward to a running version with Fermenter support. However, this needs to be added frst to cbpi4 :-)

**Comment by JamFfm** [comment]
Thank you avollkopf.
Like this it worked:

`class LCDisplay(CBPiExtension):
    def __init__(self, cbpi):
        self.cbpi = cbpi
        self._task = asyncio.create_task(self.run())

    async def run(self):
        sensor_value = self.cbpi.sensor.get_sensor_value(kettle_sensor_id).get('value')
        print(sensor_value)
`
